package iso639_3

// RetiredCodes lookup table. Keys are retired ISO 639-3 codes
var RetiredCodes = map[string]RetiredCode{
	"fri": {Id: "fri", RefName: "Western Frisian", RetReason: "C", ChangeTo: "fry", RetRemedy: "", Effective: "2007-02-01"},
	"auv": {Id: "auv", RefName: "Auvergnat", RetReason: "M", ChangeTo: "oci", RetRemedy: "", Effective: "2007-03-14"},
	"gsc": {Id: "gsc", RefName: "Gascon", RetReason: "M", ChangeTo: "oci", RetRemedy: "", Effective: "2007-03-14"},
	"lms": {Id: "lms", RefName: "Limousin", RetReason: "M", ChangeTo: "oci", RetRemedy: "", Effective: "2007-03-14"},
	"lnc": {Id: "lnc", RefName: "Languedocien", RetReason: "M", ChangeTo: "oci", RetRemedy: "", Effective: "2007-03-14"},
	"prv": {Id: "prv", RefName: "Provençal", RetReason: "M", ChangeTo: "oci", RetRemedy: "", Effective: "2007-03-14"},
	"amd": {Id: "amd", RefName: "Amapá Creole", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2007-07-18"},
	"bgh": {Id: "bgh", RefName: "Bogan", RetReason: "D", ChangeTo: "bbh", RetRemedy: "", Effective: "2007-07-18"},
	"bnh": {Id: "bnh", RefName: "Banawá", RetReason: "M", ChangeTo: "jaa", RetRemedy: "", Effective: "2007-07-18"},
	"bvs": {Id: "bvs", RefName: "Belgian Sign Language", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Langue des signes de Belgique Francophone [sfb], and Vlaamse Gebarentaal [vgt]", Effective: "2007-07-18"},
	"ccy": {Id: "ccy", RefName: "Southern Zhuang", RetReason: "S", ChangeTo: "", RetRemedy: "Split into five languages: Nong Zhuang [zhn];  Yang Zhuang [zyg]; Yongnan Zhuang [zyn]; Zuojiang Zhuang [zzj]; Dai Zhuang [zhd].", Effective: "2007-07-18"},
	"cit": {Id: "cit", RefName: "Chittagonian", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Rohingya [rhg], and Chittagonian (new identifier [ctg])", Effective: "2007-07-18"},
	"flm": {Id: "flm", RefName: "Falam Chin", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Ranglong [rnl], and Falam Chin (new identifier [cfm]).", Effective: "2007-07-18"},
	"jap": {Id: "jap", RefName: "Jaruára", RetReason: "M", ChangeTo: "jaa", RetRemedy: "", Effective: "2007-07-18"},
	"kob": {Id: "kob", RefName: "Kohoroxitari", RetReason: "M", ChangeTo: "xsu", RetRemedy: "", Effective: "2007-07-18"},
	"mob": {Id: "mob", RefName: "Moinba", RetReason: "S", ChangeTo: "", RetRemedy: "Split into five languages: Chug [cvg]; Lish [lsh];  Kalaktang Monpa [kkf]; Tawang Monpa [twm]; Sartang [onp]", Effective: "2007-07-18"},
	"mzf": {Id: "mzf", RefName: "Aiku", RetReason: "S", ChangeTo: "", RetRemedy: "Split into four languages: Ambrak [aag]; Yangum Dey [yde]; Yangum Gel [ygl]; Yangum Mon [ymo]", Effective: "2007-07-18"},
	"nhj": {Id: "nhj", RefName: "Tlalitzlipa Nahuatl", RetReason: "M", ChangeTo: "nhi", RetRemedy: "", Effective: "2007-07-18"},
	"nhs": {Id: "nhs", RefName: "Southeastern Puebla Nahuatl", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Sierra Negra Nahuatl [nsu] and Southeastern Puebla Nahuatl [npl]", Effective: "2007-07-18"},
	"occ": {Id: "occ", RefName: "Occidental", RetReason: "D", ChangeTo: "ile", RetRemedy: "", Effective: "2007-07-18"},
	"tmx": {Id: "tmx", RefName: "Tomyang", RetReason: "M", ChangeTo: "ybi", RetRemedy: "", Effective: "2007-07-18"},
	"tot": {Id: "tot", RefName: "Patla-Chicontla Totonac", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Upper Necaxa Totonac [tku] and Tecpatlán Totonac [tcw]", Effective: "2007-07-18"},
	"xmi": {Id: "xmi", RefName: "Miarrã", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2007-07-18"},
	"yib": {Id: "yib", RefName: "Yinglish", RetReason: "M", ChangeTo: "eng", RetRemedy: "", Effective: "2007-07-18"},
	"ztc": {Id: "ztc", RefName: "Lachirioag Zapotec", RetReason: "M", ChangeTo: "zty", RetRemedy: "", Effective: "2007-07-18"},
	"atf": {Id: "atf", RefName: "Atuence", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2007-08-10"},
	"bqe": {Id: "bqe", RefName: "Navarro-Labourdin Basque", RetReason: "M", ChangeTo: "eus", RetRemedy: "", Effective: "2007-08-10"},
	"bsz": {Id: "bsz", RefName: "Souletin Basque", RetReason: "M", ChangeTo: "eus", RetRemedy: "", Effective: "2007-08-10"},
	"aex": {Id: "aex", RefName: "Amerax", RetReason: "M", ChangeTo: "eng", RetRemedy: "", Effective: "2008-01-14"},
	"ahe": {Id: "ahe", RefName: "Ahe", RetReason: "M", ChangeTo: "knx", RetRemedy: "", Effective: "2008-01-14"},
	"aiz": {Id: "aiz", RefName: "Aari", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Aari [aiw] (new identifier) and Gayil [gyl]", Effective: "2008-01-14"},
	"akn": {Id: "akn", RefName: "Amikoana", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"arf": {Id: "arf", RefName: "Arafundi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: Andai [afd]; Nanubae [afk]; Tapei [afp]", Effective: "2008-01-14"},
	"azr": {Id: "azr", RefName: "Adzera", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: Adzera [adz] (new identifier), Sukurum [zsu] and Sarasira [zsa]", Effective: "2008-01-14"},
	"bcx": {Id: "bcx", RefName: "Pamona", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Pamona [pmf] (new identifier) and Batui [zbt]", Effective: "2008-01-14"},
	"bii": {Id: "bii", RefName: "Bisu", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Bisu [bzi] (new identifier) and Laomian [lwm]", Effective: "2008-01-14"},
	"bke": {Id: "bke", RefName: "Bengkulu", RetReason: "M", ChangeTo: "pse", RetRemedy: "", Effective: "2008-01-14"},
	"blu": {Id: "blu", RefName: "Hmong Njua", RetReason: "S", ChangeTo: "", RetRemedy: "Split into four languages: Hmong Njua [hnj] (new identifier); Chuanqiandian Cluster Miao [cqd]; Horned Miao [hrm]; Small Flowery Miao [sfm]", Effective: "2008-01-14"},
	"boc": {Id: "boc", RefName: "Bakung Kenyah", RetReason: "M", ChangeTo: "xkl", RetRemedy: "", Effective: "2008-01-14"},
	"bsd": {Id: "bsd", RefName: "Sarawak Bisaya", RetReason: "M", ChangeTo: "bsb", RetRemedy: "", Effective: "2008-01-14"},
	"bwv": {Id: "bwv", RefName: "Bahau River Kenyah", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"bxt": {Id: "bxt", RefName: "Buxinhua", RetReason: "D", ChangeTo: "bgk", RetRemedy: "", Effective: "2008-01-14"},
	"byu": {Id: "byu", RefName: "Buyang", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: E'ma Buyang [yzg]; Langnian Buyang [yln]; Baha Buyang [yha]", Effective: "2008-01-14"},
	"ccx": {Id: "ccx", RefName: "Northern Zhuang", RetReason: "S", ChangeTo: "", RetRemedy: "Split into ten languages: Guibian Zh [zgn]; Liujiang Zh [zlj]; Qiubei Zh [zqe]; Guibei Zh [zgb]; Youjiang Zh [zyj]; Central Hongshuihe Zh [zch]; Eastern Hongshuihe Zh [zeh]; Liuqian Zh [zlq]; Yongbei Zh [zyb]; Lianshan Zh [zln].", Effective: "2008-01-14"},
	"cru": {Id: "cru", RefName: "Carútana", RetReason: "M", ChangeTo: "bwi", RetRemedy: "", Effective: "2008-01-14"},
	"dat": {Id: "dat", RefName: "Darang Deng", RetReason: "D", ChangeTo: "mhu", RetRemedy: "", Effective: "2008-01-14"},
	"dyk": {Id: "dyk", RefName: "Land Dayak", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"eni": {Id: "eni", RefName: "Enim", RetReason: "M", ChangeTo: "pse", RetRemedy: "", Effective: "2008-01-14"},
	"fiz": {Id: "fiz", RefName: "Izere", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Ganang [gne] and Izere [izr] (new identifier)", Effective: "2008-01-14"},
	"gen": {Id: "gen", RefName: "Geman Deng", RetReason: "D", ChangeTo: "mxj", RetRemedy: "", Effective: "2008-01-14"},
	"ggh": {Id: "ggh", RefName: "Garreh-Ajuran", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"itu": {Id: "itu", RefName: "Itutang", RetReason: "M", ChangeTo: "mzu", RetRemedy: "", Effective: "2008-01-14"},
	"kds": {Id: "kds", RefName: "Lahu Shi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Kucong [lkc] and Lahu Shi [lhi] (new identifier)", Effective: "2008-01-14"},
	"knh": {Id: "knh", RefName: "Kayan River Kenyah", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"krg": {Id: "krg", RefName: "North Korowai", RetReason: "M", ChangeTo: "khe", RetRemedy: "", Effective: "2008-01-14"},
	"krq": {Id: "krq", RefName: "Krui", RetReason: "M", ChangeTo: "ljp", RetRemedy: "", Effective: "2008-01-14"},
	"kxg": {Id: "kxg", RefName: "Katingan", RetReason: "M", ChangeTo: "nij", RetRemedy: "", Effective: "2008-01-14"},
	"lmt": {Id: "lmt", RefName: "Lematang", RetReason: "M", ChangeTo: "mui", RetRemedy: "", Effective: "2008-01-14"},
	"lnt": {Id: "lnt", RefName: "Lintang", RetReason: "M", ChangeTo: "pse", RetRemedy: "", Effective: "2008-01-14"},
	"lod": {Id: "lod", RefName: "Berawan", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: West Berawan [zbw], Central Berawan [zbc], and East Berawan [zbe]", Effective: "2008-01-14"},
	"mbg": {Id: "mbg", RefName: "Northern Nambikuára", RetReason: "S", ChangeTo: "", RetRemedy: "Split into six languages: Alapmunte [apv]; Lakondê [lkd]; Latundê [ltn]; Mamaindé [wmd]; Tawandê [xtw]; Yalakalore [xyl]", Effective: "2008-01-14"},
	"mdo": {Id: "mdo", RefName: "Southwest Gbaya", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Southwest Gbaya [gso] (new identifier) and Gbaya-Mbodomo [gmm]", Effective: "2008-01-14"},
	"mhv": {Id: "mhv", RefName: "Arakanese", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Marma [rmz] and Rakhine [rki]", Effective: "2008-01-14"},
	"miv": {Id: "miv", RefName: "Mimi", RetReason: "M", ChangeTo: "amj", RetRemedy: "", Effective: "2008-01-14"},
	"mqd": {Id: "mqd", RefName: "Madang", RetReason: "M", ChangeTo: "xkl", RetRemedy: "", Effective: "2008-01-14"},
	"nky": {Id: "nky", RefName: "Khiamniungan Naga", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: Khiamniungan Naga [kix] (new identifier); Para Naga [pzn]; Makuri Naga [jmn]", Effective: "2008-01-14"},
	"nxj": {Id: "nxj", RefName: "Nyadu", RetReason: "M", ChangeTo: "byd", RetRemedy: "", Effective: "2008-01-14"},
	"ogn": {Id: "ogn", RefName: "Ogan", RetReason: "M", ChangeTo: "pse", RetRemedy: "", Effective: "2008-01-14"},
	"ork": {Id: "ork", RefName: "Orokaiva", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Orokaiva [okv] (new identifier), Aeka [aez] and Hunjara-Kaina Ke [hkk]", Effective: "2008-01-14"},
	"paj": {Id: "paj", RefName: "Ipeka-Tapuia", RetReason: "M", ChangeTo: "kpc", RetRemedy: "", Effective: "2008-01-14"},
	"pec": {Id: "pec", RefName: "Southern Pesisir", RetReason: "M", ChangeTo: "ljp", RetRemedy: "", Effective: "2008-01-14"},
	"pen": {Id: "pen", RefName: "Penesak", RetReason: "M", ChangeTo: "mui", RetRemedy: "", Effective: "2008-01-14"},
	"plm": {Id: "plm", RefName: "Palembang", RetReason: "M", ChangeTo: "mui", RetRemedy: "", Effective: "2008-01-14"},
	"poj": {Id: "poj", RefName: "Lower Pokomo", RetReason: "M", ChangeTo: "pkb", RetRemedy: "", Effective: "2008-01-14"},
	"pun": {Id: "pun", RefName: "Pubian", RetReason: "M", ChangeTo: "ljp", RetRemedy: "", Effective: "2008-01-14"},
	"rae": {Id: "rae", RefName: "Ranau", RetReason: "M", ChangeTo: "ljp", RetRemedy: "", Effective: "2008-01-14"},
	"rjb": {Id: "rjb", RefName: "Rajbanshi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Kamta (India) / Rangpuri (Bangladesh) [rkt] and Rajbanshi (Nepal) [rjs]", Effective: "2008-01-14"},
	"rws": {Id: "rws", RefName: "Rawas", RetReason: "M", ChangeTo: "mui", RetRemedy: "", Effective: "2008-01-14"},
	"sdd": {Id: "sdd", RefName: "Semendo", RetReason: "M", ChangeTo: "pse", RetRemedy: "", Effective: "2008-01-14"},
	"sdi": {Id: "sdi", RefName: "Sindang Kelingi", RetReason: "M", ChangeTo: "liw", RetRemedy: "", Effective: "2008-01-14"},
	"skl": {Id: "skl", RefName: "Selako", RetReason: "M", ChangeTo: "knx", RetRemedy: "", Effective: "2008-01-14"},
	"slb": {Id: "slb", RefName: "Kahumamahon Saluan", RetReason: "M", ChangeTo: "loe", RetRemedy: "", Effective: "2008-01-14"},
	"srj": {Id: "srj", RefName: "Serawai", RetReason: "M", ChangeTo: "pse", RetRemedy: "", Effective: "2008-01-14"},
	"suf": {Id: "suf", RefName: "Tarpia", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Tarpia [tpf] (new identifier) and Kaptiau [kbi]", Effective: "2008-01-14"},
	"suh": {Id: "suh", RefName: "Suba", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Suba [sxb] (Kenya) and Suba-Simbita [ssc] (Tanzania)", Effective: "2008-01-14"},
	"suu": {Id: "suu", RefName: "Sungkai", RetReason: "M", ChangeTo: "ljp", RetRemedy: "", Effective: "2008-01-14"},
	"szk": {Id: "szk", RefName: "Sizaki", RetReason: "M", ChangeTo: "ikz", RetRemedy: "", Effective: "2008-01-14"},
	"tle": {Id: "tle", RefName: "Southern Marakwet", RetReason: "D", ChangeTo: "enb", RetRemedy: "", Effective: "2008-01-14"},
	"tnj": {Id: "tnj", RefName: "Tanjong", RetReason: "M", ChangeTo: "kxn", RetRemedy: "", Effective: "2008-01-14"},
	"ttx": {Id: "ttx", RefName: "Tutong 1", RetReason: "M", ChangeTo: "bsb", RetRemedy: "", Effective: "2008-01-14"},
	"ubm": {Id: "ubm", RefName: "Upper Baram Kenyah", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"vky": {Id: "vky", RefName: "Kayu Agung", RetReason: "M", ChangeTo: "kge", RetRemedy: "", Effective: "2008-01-14"},
	"vmo": {Id: "vmo", RefName: "Muko-Muko", RetReason: "M", ChangeTo: "min", RetRemedy: "", Effective: "2008-01-14"},
	"wre": {Id: "wre", RefName: "Ware", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"xah": {Id: "xah", RefName: "Kahayan", RetReason: "M", ChangeTo: "nij", RetRemedy: "", Effective: "2008-01-14"},
	"xkm": {Id: "xkm", RefName: "Mahakam Kenyah", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2008-01-14"},
	"xuf": {Id: "xuf", RefName: "Kunfal", RetReason: "M", ChangeTo: "awn", RetRemedy: "", Effective: "2008-01-14"},
	"yio": {Id: "yio", RefName: "Dayao Yi", RetReason: "M", ChangeTo: "lpo", RetRemedy: "", Effective: "2008-01-14"},
	"ymj": {Id: "ymj", RefName: "Muji Yi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into five languages: Muji, Southern [ymc], Mojii [ymi], Qila Muji [ymq], Northern Muji [ymx], and Muzi [ymz]", Effective: "2008-01-14"},
	"ypl": {Id: "ypl", RefName: "Pula Yi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: Phola [ypg], Phala [ypa] and Alo Phola [ypo]", Effective: "2008-01-14"},
	"ypw": {Id: "ypw", RefName: "Puwa Yi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: Hlepho Phowa [yhl], Labo Phowa [ypb], and Ani Phowa [ypn]", Effective: "2008-01-14"},
	"ywm": {Id: "ywm", RefName: "Wumeng Yi", RetReason: "M", ChangeTo: "ywu", RetRemedy: "", Effective: "2008-01-14"},
	"yym": {Id: "yym", RefName: "Yuanjiang-Mojiang Yi", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Southern Nisu [nsd] and Southwestern Nisu [nsv]", Effective: "2008-01-14"},
	"mly": {Id: "mly", RefName: "Malay (individual language)", RetReason: "S", ChangeTo: "", RetRemedy: "Split into four languages: Standard Malay [zsm], Haji [hji], Papuan Malay [pmy] and Malay (individual language) [zlm]", Effective: "2008-02-18"},
	"muw": {Id: "muw", RefName: "Mundari", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Munda [unx] and Mundari [unr] (new identifier)", Effective: "2008-02-18"},
	"xst": {Id: "xst", RefName: "Silt'e", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Wolane [wle] and Silt'e [stv] (new identifier)", Effective: "2008-02-28"},
	"ope": {Id: "ope", RefName: "Old Persian", RetReason: "D", ChangeTo: "peo", RetRemedy: "", Effective: "2008-04-18"},
	"scc": {Id: "scc", RefName: "Serbian", RetReason: "D", ChangeTo: "srp", RetRemedy: "", Effective: "2008-06-28"},
	"scr": {Id: "scr", RefName: "Croatian", RetReason: "D", ChangeTo: "hrv", RetRemedy: "", Effective: "2008-06-28"},
	"xsk": {Id: "xsk", RefName: "Sakan", RetReason: "D", ChangeTo: "kho", RetRemedy: "", Effective: "2008-10-23"},
	"mol": {Id: "mol", RefName: "Moldavian", RetReason: "M", ChangeTo: "ron", RetRemedy: "", Effective: "2008-11-03"},
	"aay": {Id: "aay", RefName: "Aariya", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2009-01-16"},
	"acc": {Id: "acc", RefName: "Cubulco Achí", RetReason: "M", ChangeTo: "acr", RetRemedy: "", Effective: "2009-01-16"},
	"cbm": {Id: "cbm", RefName: "Yepocapa Southwestern Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"chs": {Id: "chs", RefName: "Chumash", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2009-01-16"},
	"ckc": {Id: "ckc", RefName: "Northern Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"ckd": {Id: "ckd", RefName: "South Central Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"cke": {Id: "cke", RefName: "Eastern Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"ckf": {Id: "ckf", RefName: "Southern Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"cki": {Id: "cki", RefName: "Santa María De Jesús Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"ckj": {Id: "ckj", RefName: "Santo Domingo Xenacoj Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"ckk": {Id: "ckk", RefName: "Acatenango Southwestern Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"ckw": {Id: "ckw", RefName: "Western Cakchiquel", RetReason: "M", ChangeTo: "cak", RetRemedy: "", Effective: "2009-01-16"},
	"cnm": {Id: "cnm", RefName: "Ixtatán Chuj", RetReason: "M", ChangeTo: "cac", RetRemedy: "", Effective: "2009-01-16"},
	"cti": {Id: "cti", RefName: "Tila Chol", RetReason: "M", ChangeTo: "ctu", RetRemedy: "", Effective: "2009-01-16"},
	"cun": {Id: "cun", RefName: "Cunén Quiché", RetReason: "M", ChangeTo: "quc", RetRemedy: "", Effective: "2009-01-16"},
	"eml": {Id: "eml", RefName: "Emiliano-Romagnolo", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Emilian [egl] and Romagnol [rgn]", Effective: "2009-01-16"},
	"eur": {Id: "eur", RefName: "Europanto", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2009-01-16"},
	"gmo": {Id: "gmo", RefName: "Gamo-Gofa-Dawro", RetReason: "S", ChangeTo: "", RetRemedy: "Split into three languages: Gamo [gmv], Gofa [gof], and Dawro [dwr]", Effective: "2009-01-16"},
	"hsf": {Id: "hsf", RefName: "Southeastern Huastec", RetReason: "M", ChangeTo: "hus", RetRemedy: "", Effective: "2009-01-16"},
	"hva": {Id: "hva", RefName: "San Luís Potosí Huastec", RetReason: "M", ChangeTo: "hus", RetRemedy: "", Effective: "2009-01-16"},
	"ixi": {Id: "ixi", RefName: "Nebaj Ixil", RetReason: "M", ChangeTo: "ixl", RetRemedy: "", Effective: "2009-01-16"},
	"ixj": {Id: "ixj", RefName: "Chajul Ixil", RetReason: "M", ChangeTo: "ixl", RetRemedy: "", Effective: "2009-01-16"},
	"jai": {Id: "jai", RefName: "Western Jacalteco", RetReason: "M", ChangeTo: "jac", RetRemedy: "", Effective: "2009-01-16"},
	"mms": {Id: "mms", RefName: "Southern Mam", RetReason: "M", ChangeTo: "mam", RetRemedy: "", Effective: "2009-01-16"},
	"mpf": {Id: "mpf", RefName: "Tajumulco Mam", RetReason: "M", ChangeTo: "mam", RetRemedy: "", Effective: "2009-01-16"},
	"mtz": {Id: "mtz", RefName: "Tacanec", RetReason: "M", ChangeTo: "mam", RetRemedy: "", Effective: "2009-01-16"},
	"mvc": {Id: "mvc", RefName: "Central Mam", RetReason: "M", ChangeTo: "mam", RetRemedy: "", Effective: "2009-01-16"},
	"mvj": {Id: "mvj", RefName: "Todos Santos Cuchumatán Mam", RetReason: "M", ChangeTo: "mam", RetRemedy: "", Effective: "2009-01-16"},
	"poa": {Id: "poa", RefName: "Eastern Pokomam", RetReason: "M", ChangeTo: "poc", RetRemedy: "", Effective: "2009-01-16"},
	"pob": {Id: "pob", RefName: "Western Pokomchí", RetReason: "M", ChangeTo: "poh", RetRemedy: "", Effective: "2009-01-16"},
	"pou": {Id: "pou", RefName: "Southern Pokomam", RetReason: "M", ChangeTo: "poc", RetRemedy: "", Effective: "2009-01-16"},
	"ppv": {Id: "ppv", RefName: "Papavô", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2009-01-16"},
	"quj": {Id: "quj", RefName: "Joyabaj Quiché", RetReason: "M", ChangeTo: "quc", RetRemedy: "", Effective: "2009-01-16"},
	"qut": {Id: "qut", RefName: "West Central Quiché", RetReason: "M", ChangeTo: "quc", RetRemedy: "", Effective: "2009-01-16"},
	"quu": {Id: "quu", RefName: "Eastern Quiché", RetReason: "M", ChangeTo: "quc", RetRemedy: "", Effective: "2009-01-16"},
	"qxi": {Id: "qxi", RefName: "San Andrés Quiché", RetReason: "M", ChangeTo: "quc", RetRemedy: "", Effective: "2009-01-16"},
	"sic": {Id: "sic", RefName: "Malinguat", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Keak [keh] and Sos Kundi [sdk]", Effective: "2009-01-16"},
	"stc": {Id: "stc", RefName: "Santa Cruz", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Natügu [ntu] and Nalögo [nlz]", Effective: "2009-01-16"},
	"tlz": {Id: "tlz", RefName: "Toala'", RetReason: "M", ChangeTo: "rob", RetRemedy: "", Effective: "2009-01-16"},
	"tzb": {Id: "tzb", RefName: "Bachajón Tzeltal", RetReason: "M", ChangeTo: "tzh", RetRemedy: "", Effective: "2009-01-16"},
	"tzc": {Id: "tzc", RefName: "Chamula Tzotzil", RetReason: "M", ChangeTo: "tzo", RetRemedy: "", Effective: "2009-01-16"},
	"tze": {Id: "tze", RefName: "Chenalhó Tzotzil", RetReason: "M", ChangeTo: "tzo", RetRemedy: "", Effective: "2009-01-16"},
	"tzs": {Id: "tzs", RefName: "San Andrés Larrainzar Tzotzil", RetReason: "M", ChangeTo: "tzo", RetRemedy: "", Effective: "2009-01-16"},
	"tzt": {Id: "tzt", RefName: "Western Tzutujil", RetReason: "M", ChangeTo: "tzj", RetRemedy: "", Effective: "2009-01-16"},
	"tzu": {Id: "tzu", RefName: "Huixtán Tzotzil", RetReason: "M", ChangeTo: "tzo", RetRemedy: "", Effective: "2009-01-16"},
	"tzz": {Id: "tzz", RefName: "Zinacantán Tzotzil", RetReason: "M", ChangeTo: "tzo", RetRemedy: "", Effective: "2009-01-16"},
	"vlr": {Id: "vlr", RefName: "Vatrata", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Vera'a [vra] and Lemerig [lrz]", Effective: "2009-01-16"},
	"yus": {Id: "yus", RefName: "Chan Santa Cruz Maya", RetReason: "M", ChangeTo: "yua", RetRemedy: "", Effective: "2009-01-16"},
	"nfg": {Id: "nfg", RefName: "Nyeng", RetReason: "M", ChangeTo: "nfd", RetRemedy: "", Effective: "2009-01-26"},
	"nfk": {Id: "nfk", RefName: "Shakara", RetReason: "M", ChangeTo: "nfd", RetRemedy: "", Effective: "2009-01-26"},
	"agp": {Id: "agp", RefName: "Paranan", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Pahanan Agta [apf] and Paranan [prf] (new identifier)", Effective: "2010-01-18"},
	"bhk": {Id: "bhk", RefName: "Albay Bicolano", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Buhi'non Bikol [ubl]; Libon Bikol [lbl]; Miraya Bikol [rbl]; West Albay Bikol [fbl]", Effective: "2010-01-18"},
	"bkb": {Id: "bkb", RefName: "Finallig", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Eastern Bontok [ebk] and Southern Bontok [obk]", Effective: "2010-01-18"},
	"btb": {Id: "btb", RefName: "Beti (Cameroon)", RetReason: "D", ChangeTo: "beb", RetRemedy: "", Effective: "2010-01-18"},
	"cjr": {Id: "cjr", RefName: "Chorotega", RetReason: "M", ChangeTo: "mom", RetRemedy: "", Effective: "2010-01-18"},
	"cmk": {Id: "cmk", RefName: "Chimakum", RetReason: "D", ChangeTo: "xch", RetRemedy: "", Effective: "2010-01-18"},
	"drh": {Id: "drh", RefName: "Darkhat", RetReason: "M", ChangeTo: "khk", RetRemedy: "", Effective: "2010-01-18"},
	"drw": {Id: "drw", RefName: "Darwazi", RetReason: "M", ChangeTo: "prs", RetRemedy: "", Effective: "2010-01-18"},
	"gav": {Id: "gav", RefName: "Gabutamon", RetReason: "M", ChangeTo: "dev", RetRemedy: "", Effective: "2010-01-18"},
	"mof": {Id: "mof", RefName: "Mohegan-Montauk-Narragansett", RetReason: "S", ChangeTo: "", RetRemedy: "split into Mohegan-Pequot [xpq] and Narragansett [xnt]", Effective: "2010-01-18"},
	"mst": {Id: "mst", RefName: "Cataelano Mandaya", RetReason: "M", ChangeTo: "mry", RetRemedy: "", Effective: "2010-01-18"},
	"myt": {Id: "myt", RefName: "Sangab Mandaya", RetReason: "M", ChangeTo: "mry", RetRemedy: "", Effective: "2010-01-18"},
	"rmr": {Id: "rmr", RefName: "Caló", RetReason: "S", ChangeTo: "", RetRemedy: "split into Caló [rmq] and Erromintxela [emx]", Effective: "2010-01-18"},
	"sgl": {Id: "sgl", RefName: "Sanglechi-Ishkashimi", RetReason: "S", ChangeTo: "", RetRemedy: "split into Sanglechi [sgy] and Ishkashimi [isk]", Effective: "2010-01-18"},
	"sul": {Id: "sul", RefName: "Surigaonon", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Tandaganon [tgn] and Surigaonon [sgd] (new identifier)", Effective: "2010-01-18"},
	"sum": {Id: "sum", RefName: "Sumo-Mayangna", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Mayangna [yan] and Ulwa [ulw]", Effective: "2010-01-18"},
	"tnf": {Id: "tnf", RefName: "Tangshewi", RetReason: "M", ChangeTo: "prs", RetRemedy: "", Effective: "2010-01-18"},
	"wgw": {Id: "wgw", RefName: "Wagawaga", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Yaleba [ylb] and Wagawaga [wgb] (new identifier)", Effective: "2010-01-18"},
	"ayx": {Id: "ayx", RefName: "Ayi (China)", RetReason: "D", ChangeTo: "nun", RetRemedy: "", Effective: "2011-05-18"},
	"bjq": {Id: "bjq", RefName: "Southern Betsimisaraka Malagasy", RetReason: "S", ChangeTo: "", RetRemedy: "split into Southern Betsimisaraka [bzc] and Tesaka Malagasy [tkg]", Effective: "2011-05-18"},
	"dha": {Id: "dha", RefName: "Dhanwar (India)", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2011-05-18"},
	"dkl": {Id: "dkl", RefName: "Kolum So Dogon", RetReason: "S", ChangeTo: "", RetRemedy: "split into Ampari Dogon [aqd] and Mombo Dogon [dmb]", Effective: "2011-05-18"},
	"mja": {Id: "mja", RefName: "Mahei", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2011-05-18"},
	"nbf": {Id: "nbf", RefName: "Naxi", RetReason: "S", ChangeTo: "", RetRemedy: "split into Naxi [nxq] and Narua [nru]", Effective: "2011-05-18"},
	"noo": {Id: "noo", RefName: "Nootka", RetReason: "S", ChangeTo: "", RetRemedy: "Split into [dtd] Ditidaht and [nuk] Nuu-chah-nulth", Effective: "2011-05-18"},
	"tie": {Id: "tie", RefName: "Tingal", RetReason: "M", ChangeTo: "ras", RetRemedy: "", Effective: "2011-05-18"},
	"tkk": {Id: "tkk", RefName: "Takpa", RetReason: "D", ChangeTo: "twm", RetRemedy: "", Effective: "2011-05-18"},
	"baz": {Id: "baz", RefName: "Tunen", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Tunen [tvu] and Nyokon [nvo]", Effective: "2012-02-03"},
	"bjd": {Id: "bjd", RefName: "Bandjigali", RetReason: "M", ChangeTo: "drl", RetRemedy: "", Effective: "2012-02-03"},
	"ccq": {Id: "ccq", RefName: "Chaungtha", RetReason: "M", ChangeTo: "rki", RetRemedy: "", Effective: "2012-02-03"},
	"cka": {Id: "cka", RefName: "Khumi Awa Chin", RetReason: "M", ChangeTo: "cmr", RetRemedy: "", Effective: "2012-02-03"},
	"dap": {Id: "dap", RefName: "Nisi (India)", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Nyishi [njz] and Tagin [tgj]", Effective: "2012-02-03"},
	"dwl": {Id: "dwl", RefName: "Walo Kumbe Dogon", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Dogon, Bankan Tey (Walo) [dbw]  and Dogon, Ben Tey (Beni) [dbt]", Effective: "2012-02-03"},
	"elp": {Id: "elp", RefName: "Elpaputih", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2012-02-03"},
	"gbc": {Id: "gbc", RefName: "Garawa", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Garrwa [wrk] and Wanyi [wny]", Effective: "2012-02-03"},
	"gio": {Id: "gio", RefName: "Gelao", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Qau [gqu] and A'ou [aou] with some going to Green Gelao [gig], some to Red Gelao [gir], and some to White Gelao [giw]", Effective: "2012-02-03"},
	"hrr": {Id: "hrr", RefName: "Horuru", RetReason: "M", ChangeTo: "jal", RetRemedy: "", Effective: "2012-02-03"},
	"ibi": {Id: "ibi", RefName: "Ibilo", RetReason: "M", ChangeTo: "opa", RetRemedy: "", Effective: "2012-02-03"},
	"jar": {Id: "jar", RefName: "Jarawa (Nigeria)", RetReason: "S", ChangeTo: "", RetRemedy: "split into Gwak [jgk] and Bankal [jjr]", Effective: "2012-02-03"},
	"kdv": {Id: "kdv", RefName: "Kado", RetReason: "S", ChangeTo: "", RetRemedy: "split into Kadu [zkd] and Kanan [zkn]", Effective: "2012-02-03"},
	"kgh": {Id: "kgh", RefName: "Upper Tanudan Kalinga", RetReason: "M", ChangeTo: "kml", RetRemedy: "", Effective: "2012-02-03"},
	"kpp": {Id: "kpp", RefName: "Paku Karen", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Paku Karen [jkp] and Mobwa Karen [jkm]", Effective: "2012-02-03"},
	"kzh": {Id: "kzh", RefName: "Kenuzi-Dongola", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Andaandi (Dongolawi) [dgl] and Kenzi (Mattoki) [xnz]", Effective: "2012-02-03"},
	"lcq": {Id: "lcq", RefName: "Luhu", RetReason: "M", ChangeTo: "ppr", RetRemedy: "", Effective: "2012-02-03"},
	"mgx": {Id: "mgx", RefName: "Omati", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Barikewa [jbk] and Mouwase [jmw]", Effective: "2012-02-03"},
	"nln": {Id: "nln", RefName: "Durango Nahuatl", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Eastern Durango Nahuatl [azd] and Western Durango Nahuatl [azn]", Effective: "2012-02-03"},
	"pbz": {Id: "pbz", RefName: "Palu", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2012-02-03"},
	"pgy": {Id: "pgy", RefName: "Pongyong", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2012-02-03"},
	"sca": {Id: "sca", RefName: "Sansu", RetReason: "M", ChangeTo: "hle", RetRemedy: "", Effective: "2012-02-03"},
	"tlw": {Id: "tlw", RefName: "South Wemale", RetReason: "M", ChangeTo: "weo", RetRemedy: "", Effective: "2012-02-03"},
	"unp": {Id: "unp", RefName: "Worora", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Worrorra [wro] and Unggumi [xgu].", Effective: "2012-02-03"},
	"wiw": {Id: "wiw", RefName: "Wirangu", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Wirangu [wgu] and Nauo [nwo]", Effective: "2012-02-03"},
	"ybd": {Id: "ybd", RefName: "Yangbye", RetReason: "M", ChangeTo: "rki", RetRemedy: "", Effective: "2012-02-03"},
	"yen": {Id: "yen", RefName: "Yendang", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Yendang [ynq] and Yotti [yot]", Effective: "2012-02-03"},
	"yma": {Id: "yma", RefName: "Yamphe", RetReason: "M", ChangeTo: "lrr", RetRemedy: "", Effective: "2012-02-03"},
	"daf": {Id: "daf", RefName: "Dan", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Dan [dnj] and Kla-Dan [lda]", Effective: "2013-01-23"},
	"djl": {Id: "djl", RefName: "Djiwarli", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Djiwarli [dze] and Thiin [iin]", Effective: "2013-01-23"},
	"ggr": {Id: "ggr", RefName: "Aghu Tharnggalu", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Aghu-Tharnggala [gtu], Gugu-Mini [ggm], and Ikarranggal [ikr]", Effective: "2013-01-23"},
	"ilw": {Id: "ilw", RefName: "Talur", RetReason: "M", ChangeTo: "gal", RetRemedy: "", Effective: "2013-01-23"},
	"izi": {Id: "izi", RefName: "Izi-Ezaa-Ikwo-Mgbo", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Izii [izz], Ezaa [eza], Ikwo [iqw], Mgbolizhia [gmz]", Effective: "2013-01-23"},
	"meg": {Id: "meg", RefName: "Mea", RetReason: "M", ChangeTo: "cir", RetRemedy: "", Effective: "2013-01-23"},
	"mld": {Id: "mld", RefName: "Malakhel", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2013-01-23"},
	"mnt": {Id: "mnt", RefName: "Maykulan", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Mayi-Kulan [xyk], Mayi-Thakurti [xyt], Mayi-Yapi [xyj], and Wunumara [wnn]", Effective: "2013-01-23"},
	"mwd": {Id: "mwd", RefName: "Mudbura", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Karranga [xrq] and Mudburra [dmw]", Effective: "2013-01-23"},
	"myq": {Id: "myq", RefName: "Forest Maninka", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2013-01-23"},
	"nbx": {Id: "nbx", RefName: "Ngura", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Eastern Karnic [ekc], Garlali [gll], Punthamara [xpt], Wangkumara [xwk], and Badjiri [jbi]", Effective: "2013-01-23"},
	"nlr": {Id: "nlr", RefName: "Ngarla", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Ngarla [nrk] and Yinhawangka [ywg]", Effective: "2013-01-23"},
	"pcr": {Id: "pcr", RefName: "Panang", RetReason: "M", ChangeTo: "adx", RetRemedy: "", Effective: "2013-01-23"},
	"ppr": {Id: "ppr", RefName: "Piru", RetReason: "M", ChangeTo: "lcq", RetRemedy: "", Effective: "2013-01-23"},
	"tgg": {Id: "tgg", RefName: "Tangga", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Fanamaket [bjp], Niwer Mil [hrc], and Warwar Feni [hrw]", Effective: "2013-01-23"},
	"wit": {Id: "wit", RefName: "Wintu", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Wintu [wnw], Nomlaki [nol], and Patwin [pwi]", Effective: "2013-01-23"},
	"xia": {Id: "xia", RefName: "Xiandao", RetReason: "M", ChangeTo: "acn", RetRemedy: "", Effective: "2013-01-23"},
	"yiy": {Id: "yiy", RefName: "Yir Yoront", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Yir Yoront [yyr] and Yirrk-Mel [yrm]", Effective: "2013-01-23"},
	"yos": {Id: "yos", RefName: "Yos", RetReason: "M", ChangeTo: "zom", RetRemedy: "", Effective: "2013-01-23"},
	"emo": {Id: "emo", RefName: "Emok", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2014-02-03"},
	"ggm": {Id: "ggm", RefName: "Gugu Mini", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2014-02-03"},
	"leg": {Id: "leg", RefName: "Lengua", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Enlhet [enl] and Enxet [enx]", Effective: "2014-02-03"},
	"lmm": {Id: "lmm", RefName: "Lamam", RetReason: "D", ChangeTo: "rmx", RetRemedy: "", Effective: "2014-02-03"},
	"mhh": {Id: "mhh", RefName: "Maskoy Pidgin", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2014-02-03"},
	"puz": {Id: "puz", RefName: "Purum Naga", RetReason: "M", ChangeTo: "pub", RetRemedy: "", Effective: "2014-02-03"},
	"sap": {Id: "sap", RefName: "Sanapaná", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Sanapaná [spn] and Angaité [aqt]", Effective: "2014-02-03"},
	"yuu": {Id: "yuu", RefName: "Yugh", RetReason: "D", ChangeTo: "yug", RetRemedy: "", Effective: "2014-02-03"},
	"aam": {Id: "aam", RefName: "Aramanik", RetReason: "M", ChangeTo: "aas", RetRemedy: "", Effective: "2015-01-12"},
	"adp": {Id: "adp", RefName: "Adap", RetReason: "M", ChangeTo: "dzo", RetRemedy: "", Effective: "2015-01-12"},
	"aue": {Id: "aue", RefName: "ǂKxʼauǁʼein", RetReason: "D", ChangeTo: "ktz", RetRemedy: "", Effective: "2015-01-12"},
	"bmy": {Id: "bmy", RefName: "Bemba (Democratic Republic of Congo)", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"bxx": {Id: "bxx", RefName: "Borna (Democratic Republic of Congo)", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"byy": {Id: "byy", RefName: "Buya", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"dzd": {Id: "dzd", RefName: "Daza", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"gfx": {Id: "gfx", RefName: "Mangetti Dune ǃXung", RetReason: "M", ChangeTo: "vaj", RetRemedy: "", Effective: "2015-01-12"},
	"gti": {Id: "gti", RefName: "Gbati-ri", RetReason: "M", ChangeTo: "nyc", RetRemedy: "", Effective: "2015-01-12"},
	"ime": {Id: "ime", RefName: "Imeraguen", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"kbf": {Id: "kbf", RefName: "Kakauhua", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"koj": {Id: "koj", RefName: "Sara Dunjo", RetReason: "M", ChangeTo: "kwv", RetRemedy: "", Effective: "2015-01-12"},
	"kwq": {Id: "kwq", RefName: "Kwak", RetReason: "M", ChangeTo: "yam", RetRemedy: "", Effective: "2015-01-12"},
	"kxe": {Id: "kxe", RefName: "Kakihum", RetReason: "M", ChangeTo: "tvd", RetRemedy: "", Effective: "2015-01-12"},
	"lii": {Id: "lii", RefName: "Lingkhim", RetReason: "M", ChangeTo: "raq", RetRemedy: "", Effective: "2015-01-12"},
	"mwj": {Id: "mwj", RefName: "Maligo", RetReason: "M", ChangeTo: "vaj", RetRemedy: "", Effective: "2015-01-12"},
	"nnx": {Id: "nnx", RefName: "Ngong", RetReason: "M", ChangeTo: "ngv", RetRemedy: "", Effective: "2015-01-12"},
	"oun": {Id: "oun", RefName: "ǃOǃung", RetReason: "M", ChangeTo: "vaj", RetRemedy: "", Effective: "2015-01-12"},
	"pmu": {Id: "pmu", RefName: "Mirpur Panjabi", RetReason: "M", ChangeTo: "phr", RetRemedy: "", Effective: "2015-01-12"},
	"sgo": {Id: "sgo", RefName: "Songa", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"thx": {Id: "thx", RefName: "The", RetReason: "D", ChangeTo: "oyb", RetRemedy: "", Effective: "2015-01-12"},
	"tsf": {Id: "tsf", RefName: "Southwestern Tamang", RetReason: "M", ChangeTo: "taj", RetRemedy: "", Effective: "2015-01-12"},
	"uok": {Id: "uok", RefName: "Uokha", RetReason: "M", ChangeTo: "ema", RetRemedy: "", Effective: "2015-01-12"},
	"xsj": {Id: "xsj", RefName: "Subi", RetReason: "D", ChangeTo: "suj", RetRemedy: "", Effective: "2015-01-12"},
	"yds": {Id: "yds", RefName: "Yiddish Sign Language", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"ymt": {Id: "ymt", RefName: "Mator-Taygi-Karagas", RetReason: "D", ChangeTo: "mtm", RetRemedy: "", Effective: "2015-01-12"},
	"ynh": {Id: "ynh", RefName: "Yangho", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2015-01-12"},
	"bgm": {Id: "bgm", RefName: "Baga Mboteni", RetReason: "D", ChangeTo: "bcg", RetRemedy: "", Effective: "2016-01-15"},
	"btl": {Id: "btl", RefName: "Bhatola", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"cbe": {Id: "cbe", RefName: "Chipiajes", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"cbh": {Id: "cbh", RefName: "Cagua", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"coy": {Id: "coy", RefName: "Coyaima", RetReason: "M", ChangeTo: "pij", RetRemedy: "", Effective: "2016-01-15"},
	"cqu": {Id: "cqu", RefName: "Chilean Quechua", RetReason: "M", ChangeTo: "quh", RetRemedy: "", Effective: "2016-01-15"},
	"cum": {Id: "cum", RefName: "Cumeral", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"duj": {Id: "duj", RefName: "Dhuwal", RetReason: "S", ChangeTo: "", RetRemedy: "split into [dwu] Dhuwal and [dwy] Dhuwaya", Effective: "2016-01-15"},
	"ggn": {Id: "ggn", RefName: "Eastern Gurung", RetReason: "M", ChangeTo: "gvr", RetRemedy: "", Effective: "2016-01-15"},
	"ggo": {Id: "ggo", RefName: "Southern Gondi", RetReason: "S", ChangeTo: "", RetRemedy: "split into [esg] Aheri Gondi and [wsg] Adilabad Gondi", Effective: "2016-01-15"},
	"guv": {Id: "guv", RefName: "Gey", RetReason: "M", ChangeTo: "duz", RetRemedy: "", Effective: "2016-01-15"},
	"iap": {Id: "iap", RefName: "Iapama", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"ill": {Id: "ill", RefName: "Iranun", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Iranun (Philippines) [ilp] and Iranun (Malaysia) [ilm]", Effective: "2016-01-15"},
	"kgc": {Id: "kgc", RefName: "Kasseng", RetReason: "D", ChangeTo: "tdf", RetRemedy: "", Effective: "2016-01-15"},
	"kox": {Id: "kox", RefName: "Coxima", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"ktr": {Id: "ktr", RefName: "Kota Marudu Tinagas", RetReason: "M", ChangeTo: "dtp", RetRemedy: "", Effective: "2016-01-15"},
	"kvs": {Id: "kvs", RefName: "Kunggara", RetReason: "D", ChangeTo: "gdj", RetRemedy: "", Effective: "2016-01-15"},
	"kzj": {Id: "kzj", RefName: "Coastal Kadazan", RetReason: "M", ChangeTo: "dtp", RetRemedy: "", Effective: "2016-01-15"},
	"kzt": {Id: "kzt", RefName: "Tambunan Dusun", RetReason: "M", ChangeTo: "dtp", RetRemedy: "", Effective: "2016-01-15"},
	"nad": {Id: "nad", RefName: "Nijadali", RetReason: "D", ChangeTo: "xny", RetRemedy: "", Effective: "2016-01-15"},
	"nts": {Id: "nts", RefName: "Natagaimas", RetReason: "M", ChangeTo: "pij", RetRemedy: "", Effective: "2016-01-15"},
	"ome": {Id: "ome", RefName: "Omejes", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"pmc": {Id: "pmc", RefName: "Palumata", RetReason: "D", ChangeTo: "huw", RetRemedy: "", Effective: "2016-01-15"},
	"pod": {Id: "pod", RefName: "Ponares", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"ppa": {Id: "ppa", RefName: "Pao", RetReason: "M", ChangeTo: "bfy", RetRemedy: "", Effective: "2016-01-15"},
	"pry": {Id: "pry", RefName: "Pray 3", RetReason: "D", ChangeTo: "prt", RetRemedy: "", Effective: "2016-01-15"},
	"rna": {Id: "rna", RefName: "Runa", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"svr": {Id: "svr", RefName: "Savara", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"tdu": {Id: "tdu", RefName: "Tempasuk Dusun", RetReason: "M", ChangeTo: "dtp", RetRemedy: "", Effective: "2016-01-15"},
	"thc": {Id: "thc", RefName: "Tai Hang Tong", RetReason: "M", ChangeTo: "tpo", RetRemedy: "", Effective: "2016-01-15"},
	"tid": {Id: "tid", RefName: "Tidong", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Northern Tidung [ntd] and Southern Tidung [itd]", Effective: "2016-01-15"},
	"tmp": {Id: "tmp", RefName: "Tai Mène", RetReason: "M", ChangeTo: "tyj", RetRemedy: "", Effective: "2016-01-15"},
	"tne": {Id: "tne", RefName: "Tinoc Kallahan", RetReason: "M", ChangeTo: "kak", RetRemedy: "", Effective: "2016-01-15"},
	"toe": {Id: "toe", RefName: "Tomedes", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"xba": {Id: "xba", RefName: "Kamba (Brazil)", RetReason: "D", ChangeTo: "cax", RetRemedy: "", Effective: "2016-01-15"},
	"xbx": {Id: "xbx", RefName: "Kabixí", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"xip": {Id: "xip", RefName: "Xipináwa", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"xkh": {Id: "xkh", RefName: "Karahawyana", RetReason: "D", ChangeTo: "waw", RetRemedy: "", Effective: "2016-01-15"},
	"yri": {Id: "yri", RefName: "Yarí", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2016-01-15"},
	"jeg": {Id: "jeg", RefName: "Jeng", RetReason: "M", ChangeTo: "oyb", RetRemedy: "", Effective: "2017-01-31"},
	"kgd": {Id: "kgd", RefName: "Kataang", RetReason: "S", ChangeTo: "", RetRemedy: "Split into [ncq] Northern Katang and [sct] Southern Katang", Effective: "2017-01-31"},
	"krm": {Id: "krm", RefName: "Krim", RetReason: "M", ChangeTo: "bmf", RetRemedy: "", Effective: "2017-01-31"},
	"prb": {Id: "prb", RefName: "Lua'", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2017-01-31"},
	"puk": {Id: "puk", RefName: "Pu Ko", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2017-01-31"},
	"rie": {Id: "rie", RefName: "Rien", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2017-01-31"},
	"rsi": {Id: "rsi", RefName: "Rennellese Sign Language", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2017-01-31"},
	"skk": {Id: "skk", RefName: "Sok", RetReason: "M", ChangeTo: "oyb", RetRemedy: "", Effective: "2017-01-31"},
	"snh": {Id: "snh", RefName: "Shinabo", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2017-01-31"},
	"lsg": {Id: "lsg", RefName: "Lyons Sign Language", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2018-01-23"},
	"mwx": {Id: "mwx", RefName: "Mediak", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2018-01-23"},
	"mwy": {Id: "mwy", RefName: "Mosiro", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2018-01-23"},
	"ncp": {Id: "ncp", RefName: "Ndaktup", RetReason: "M", ChangeTo: "kdz", RetRemedy: "", Effective: "2018-01-23"},
	"ais": {Id: "ais", RefName: "Nataoran Amis", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Amis [ami] and Sakizaya [szy]", Effective: "2019-01-25"},
	"asd": {Id: "asd", RefName: "Asas", RetReason: "M", ChangeTo: "snz", RetRemedy: "", Effective: "2019-01-25"},
	"dit": {Id: "dit", RefName: "Dirari", RetReason: "M", ChangeTo: "dif", RetRemedy: "", Effective: "2019-01-25"},
	"dud": {Id: "dud", RefName: "Hun-Saare", RetReason: "S", ChangeTo: "", RetRemedy: "Split into ut-Hun [uth] and us-Saare [uss]", Effective: "2019-01-25"},
	"lba": {Id: "lba", RefName: "Lui", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2019-01-25"},
	"llo": {Id: "llo", RefName: "Khlor", RetReason: "D", ChangeTo: "ngt", RetRemedy: "", Effective: "2019-01-25"},
	"myd": {Id: "myd", RefName: "Maramba", RetReason: "M", ChangeTo: "aog", RetRemedy: "", Effective: "2019-01-25"},
	"myi": {Id: "myi", RefName: "Mina (India)", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2019-01-25"},
	"nns": {Id: "nns", RefName: "Ningye", RetReason: "M", ChangeTo: "nbr", RetRemedy: "", Effective: "2019-01-25"},
	"aoh": {Id: "aoh", RefName: "Arma", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"ayy": {Id: "ayy", RefName: "Tayabas Ayta", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"bbz": {Id: "bbz", RefName: "Babalia Creole Arabic", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"bpb": {Id: "bpb", RefName: "Barbacoas", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"cca": {Id: "cca", RefName: "Cauca", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"cdg": {Id: "cdg", RefName: "Chamari", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"dgu": {Id: "dgu", RefName: "Degaru", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"drr": {Id: "drr", RefName: "Dororo", RetReason: "M", ChangeTo: "kzk", RetRemedy: "", Effective: "2020-01-23"},
	"ekc": {Id: "ekc", RefName: "Eastern Karnic", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"gli": {Id: "gli", RefName: "Guliguli", RetReason: "M", ChangeTo: "kzk", RetRemedy: "", Effective: "2020-01-23"},
	"kjf": {Id: "kjf", RefName: "Khalaj", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"kxl": {Id: "kxl", RefName: "Nepali Kurux", RetReason: "M", ChangeTo: "kru", RetRemedy: "", Effective: "2020-01-23"},
	"kxu": {Id: "kxu", RefName: "Kui (India)", RetReason: "S", ChangeTo: "", RetRemedy: "Split into [dwk] Dawik Kui and [uki] Kui (India)", Effective: "2020-01-23"},
	"lmz": {Id: "lmz", RefName: "Lumbee", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"nxu": {Id: "nxu", RefName: "Narau", RetReason: "M", ChangeTo: "bpp", RetRemedy: "", Effective: "2020-01-23"},
	"plp": {Id: "plp", RefName: "Palpa", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"sdm": {Id: "sdm", RefName: "Semandang", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Semandang [sdq], Beginci [ebc] and Gerai [gef]", Effective: "2020-01-23"},
	"tbb": {Id: "tbb", RefName: "Tapeba", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2020-01-23"},
	"xrq": {Id: "xrq", RefName: "Karranga", RetReason: "M", ChangeTo: "dmw", RetRemedy: "", Effective: "2020-01-23"},
	"xtz": {Id: "xtz", RefName: "Tasmanian", RetReason: "S", ChangeTo: "", RetRemedy: "Split into [xpv] Northern Tasman,  [xph] North Midlands Tasman, [xpb] Northeastern Tasman, [xpd] Oyster Bay Tasmanian, [xpf] Southeast Tasma, [xpx] Southwestern Tasman, [xpw] Northwestern Tasman., [xpl] Port Sorell Tasman. and [xpz] Bruny Island Tasman.", Effective: "2020-01-23"},
	"zir": {Id: "zir", RefName: "Ziriya", RetReason: "D", ChangeTo: "scv", RetRemedy: "", Effective: "2020-01-23"},
	"thw": {Id: "thw", RefName: "Thudam", RetReason: "M", ChangeTo: "ola", RetRemedy: "", Effective: "2020-03-19"},
	"bic": {Id: "bic", RefName: "Bikaru", RetReason: "M", ChangeTo: "bir", RetRemedy: "", Effective: "2021-01-15"},
	"bij": {Id: "bij", RefName: "Vaghat-Ya-Bijim-Legeri", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Tiyaa [tyy], Bijim [jbm] and Kadung [dkg].", Effective: "2021-01-15"},
	"blg": {Id: "blg", RefName: "Balau", RetReason: "M", ChangeTo: "iba", RetRemedy: "", Effective: "2021-01-15"},
	"gji": {Id: "gji", RefName: "Geji", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Gyaazi [gyz], and Bu (Bauchi State) [zbu]", Effective: "2021-01-15"},
	"mvm": {Id: "mvm", RefName: "Muya", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Eastern Minyag [emq] and Western Minyag [wmg]", Effective: "2021-01-15"},
	"ngo": {Id: "ngo", RefName: "Ngoni", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Ngoni (Tanzania) [xnj] and Ngoni (Mozambique) [xnq]", Effective: "2021-01-15"},
	"pat": {Id: "pat", RefName: "Papitalai", RetReason: "M", ChangeTo: "kxr", RetRemedy: "", Effective: "2021-01-15"},
	"vki": {Id: "vki", RefName: "Ija-Zuba", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Koro Nulu [vkn] and Koro Zuba [vkz]", Effective: "2021-01-15"},
	"wra": {Id: "wra", RefName: "Warapu", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Bauni [bpe], Uni [uni] and Bouni [suo]", Effective: "2021-01-15"},
	"ajt": {Id: "ajt", RefName: "Judeo-Tunisian Arabic", RetReason: "D", ChangeTo: "aeb", RetRemedy: "", Effective: "2022-01-20"},
	"cug": {Id: "cug", RefName: "Chungmboko", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Chung [cnq] and Mbuk [bpc]", Effective: "2022-01-20"},
	"lak": {Id: "lak", RefName: "Laka (Nigeria)", RetReason: "M", ChangeTo: "ksp", RetRemedy: "", Effective: "2022-01-20"},
	"lno": {Id: "lno", RefName: "Lango (South Sudan)", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Lango [lgo], Imotong [imt], Logir [lqr] and Okolie [oie]", Effective: "2022-01-20"},
	"pii": {Id: "pii", RefName: "Pini", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2022-01-20"},
	"smd": {Id: "smd", RefName: "Sama", RetReason: "M", ChangeTo: "kmb", RetRemedy: "", Effective: "2022-01-20"},
	"snb": {Id: "snb", RefName: "Sebuyau", RetReason: "M", ChangeTo: "iba", RetRemedy: "", Effective: "2022-01-20"},
	"uun": {Id: "uun", RefName: "Kulon-Pazeh", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Kulon [uon] and Pazeh [pzh]", Effective: "2022-01-20"},
	"wrd": {Id: "wrd", RefName: "Warduji", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2022-01-20"},
	"wya": {Id: "wya", RefName: "Wyandot", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Wyandot [wyn] and Wendat [wdt]", Effective: "2022-01-20"},
	"ajp": {Id: "ajp", RefName: "South Levantine Arabic", RetReason: "M", ChangeTo: "apc", RetRemedy: "", Effective: "2023-01-20"},
	"kgm": {Id: "kgm", RefName: "Karipúna", RetReason: "D", ChangeTo: "plu", RetRemedy: "", Effective: "2023-01-20"},
	"nom": {Id: "nom", RefName: "Nocamán", RetReason: "M", ChangeTo: "cbr", RetRemedy: "", Effective: "2023-01-20"},
	"pmk": {Id: "pmk", RefName: "Pamlico", RetReason: "M", ChangeTo: "crr", RetRemedy: "", Effective: "2023-01-20"},
	"prp": {Id: "prp", RefName: "Parsi", RetReason: "M", ChangeTo: "guj", RetRemedy: "", Effective: "2023-01-20"},
	"slq": {Id: "slq", RefName: "Salchuq", RetReason: "N", ChangeTo: "", RetRemedy: "", Effective: "2023-01-20"},
	"szd": {Id: "szd", RefName: "Seru", RetReason: "M", ChangeTo: "umi", RetRemedy: "", Effective: "2023-01-20"},
	"tmk": {Id: "tmk", RefName: "Northwestern Tamang", RetReason: "M", ChangeTo: "tdg", RetRemedy: "", Effective: "2023-01-20"},
	"tpw": {Id: "tpw", RefName: "Tupí", RetReason: "D", ChangeTo: "tpn", RetRemedy: "", Effective: "2023-01-20"},
	"xss": {Id: "xss", RefName: "Assan", RetReason: "M", ChangeTo: "zko", RetRemedy: "", Effective: "2023-01-20"},
	"zkb": {Id: "zkb", RefName: "Koibal", RetReason: "D", ChangeTo: "kjh", RetRemedy: "", Effective: "2023-01-20"},
	"zua": {Id: "zua", RefName: "Zeem", RetReason: "S", ChangeTo: "", RetRemedy: "Split into [tvi] Tulai, [dyr] Dyarim, [dsk] Dokshi, [cxh] Cha'ari, and [zem] Zeem", Effective: "2023-01-20"},
	"ksa": {Id: "ksa", RefName: "Shuwa-Zamani", RetReason: "S", ChangeTo: "", RetRemedy: "Split into [rsw] Rishiwa and [izm] Kizamani", Effective: "2023-01-23"},
	"plj": {Id: "plj", RefName: "Polci", RetReason: "S", ChangeTo: "", RetRemedy: "Split into Pesse [pze], Nyamzak-Dir-Mbarimi [nzr], Zul [zlu], and Buli [uly]", Effective: "2023-01-23"},
	"dek": {Id: "dek", RefName: "Dek", RetReason: "D", ChangeTo: "sqm", RetRemedy: "", Effective: "2024-09-09"},
	"nte": {Id: "nte", RefName: "Nathembo", RetReason: "M", ChangeTo: "eko", RetRemedy: "", Effective: "2024-09-09"},
}
